<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PerformanceEvaluation.Domain\PerformanceEvaluation.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Mapping\" />
    <Folder Include="Validators\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="FluentValidation" Version="8.6.3" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="8.6.3" />
  </ItemGroup>

</Project>
