// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerformanceEvaluation.Infrastructure.Data;

#nullable disable

namespace PerformanceEvaluation.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914194719_fourth")]
    partial class fourth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.CriterionJobPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("JobPositionId")
                        .HasColumnType("int");

                    b.Property<int>("PerformanceCriterionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobPositionId");

                    b.HasIndex("PerformanceCriterionId", "JobPositionId")
                        .IsUnique();

                    b.ToTable("CriterionJobPositions");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EvaluationPeriodId")
                        .HasColumnType("int");

                    b.Property<int>("EvaluatorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EvaluationPeriodId");

                    b.HasIndex("EvaluatorId", "EmployeeId", "EvaluationPeriodId")
                        .IsUnique()
                        .HasDatabaseName("UX_Evaluations_Evaluator_Employee_Period");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.EvaluationDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int");

                    b.Property<int>("PerformanceCriterionId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("PerformanceCriterionId");

                    b.ToTable("EvaluationDetails");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.EvaluationPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EvaluationPeriods");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.EvaluatorEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EvaluatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EvaluatorId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("EvaluatorEmployees");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.JobPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("JobPositions");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.PerformanceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("PerformanceCategories");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.PerformanceCriterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PerformanceCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformanceCategoryId");

                    b.ToTable("PerformanceCriteria");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("JobPositionId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("JobPositionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.CriterionJobPosition", b =>
                {
                    b.HasOne("PerformanceEvaluation.Domain.Entities.JobPosition", "JobPosition")
                        .WithMany("CriterionDescriptions")
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PerformanceEvaluation.Domain.Entities.PerformanceCriterion", "PerformanceCriterion")
                        .WithMany("JobPositionDescriptions")
                        .HasForeignKey("PerformanceCriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosition");

                    b.Navigation("PerformanceCriterion");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.Evaluation", b =>
                {
                    b.HasOne("PerformanceEvaluation.Domain.Entities.User", "Employee")
                        .WithMany("EvaluationsReceived")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PerformanceEvaluation.Domain.Entities.EvaluationPeriod", "EvaluationPeriod")
                        .WithMany("Evaluations")
                        .HasForeignKey("EvaluationPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PerformanceEvaluation.Domain.Entities.User", "Evaluator")
                        .WithMany("EvaluationsGiven")
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("EvaluationPeriod");

                    b.Navigation("Evaluator");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.EvaluationDetail", b =>
                {
                    b.HasOne("PerformanceEvaluation.Domain.Entities.Evaluation", "Evaluation")
                        .WithMany("Details")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerformanceEvaluation.Domain.Entities.PerformanceCriterion", "PerformanceCriterion")
                        .WithMany("EvaluationDetails")
                        .HasForeignKey("PerformanceCriterionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("PerformanceCriterion");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.EvaluatorEmployee", b =>
                {
                    b.HasOne("PerformanceEvaluation.Domain.Entities.User", "Employee")
                        .WithMany("Evaluators")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PerformanceEvaluation.Domain.Entities.User", "Evaluator")
                        .WithMany("ManagedEmployees")
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Evaluator");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.PerformanceCriterion", b =>
                {
                    b.HasOne("PerformanceEvaluation.Domain.Entities.PerformanceCategory", "PerformanceCategory")
                        .WithMany("Criteria")
                        .HasForeignKey("PerformanceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformanceCategory");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.User", b =>
                {
                    b.HasOne("PerformanceEvaluation.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceEvaluation.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PerformanceEvaluation.Domain.Entities.JobPosition", "JobPosition")
                        .WithMany("Users")
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("JobPosition");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.Evaluation", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.EvaluationPeriod", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.JobPosition", b =>
                {
                    b.Navigation("CriterionDescriptions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.PerformanceCategory", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.PerformanceCriterion", b =>
                {
                    b.Navigation("EvaluationDetails");

                    b.Navigation("JobPositionDescriptions");
                });

            modelBuilder.Entity("PerformanceEvaluation.Domain.Entities.User", b =>
                {
                    b.Navigation("EvaluationsGiven");

                    b.Navigation("EvaluationsReceived");

                    b.Navigation("Evaluators");

                    b.Navigation("ManagedEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
